from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey
from datetime import datetime

from app.db.database import Base


class ApprovalRequest(Base):
    """
    Category 6 - a single lifecycle approval workflow instance.
    One or more ApprovalStep rows track its multi-level progression.
    """

    __tablename__ = "approval_requests"

    id = Column(Integer, primary_key=True, index=True)

    operation_type = Column(String(100), nullable=False)

    target_user_id = Column(String(100), nullable=True, index=True)
    target_user_email = Column(String(255), nullable=True)

    requested_by = Column(String(255), nullable=False)

    status = Column(String(50), nullable=False, default="PENDING")
    current_level = Column(Integer, nullable=False, default=1)
    required_levels = Column(Text, nullable=True)  # JSON list of role strings

    payload = Column(Text, nullable=True)  # JSON of the proposed change

    risk_score = Column(Integer, nullable=True)
    risk_band = Column(String(50), nullable=True)
    policy_source = Column(String(50), nullable=True)  # ENGINE / ENGINE_UNAVAILABLE

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)


class ApprovalStep(Base):
    """
    Category 6 - one level of a multi-level approval
    (e.g. level 1 = MANAGER, level 2 = SECURITY).
    """

    __tablename__ = "approval_steps"

    id = Column(Integer, primary_key=True, index=True)

    approval_request_id = Column(
        Integer,
        ForeignKey("approval_requests.id"),
        nullable=False,
        index=True
    )

    level = Column(Integer, nullable=False)
    approver_role = Column(String(50), nullable=False)

    approver_email = Column(String(255), nullable=True)
    decision = Column(String(50), nullable=False, default="PENDING")
    comment = Column(Text, nullable=True)

    decided_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class LifecycleOperation(Base):
    """
    Category 7 - tracks a single lifecycle operation through
    dry-run -> (approval) -> execution -> verification.
    """

    __tablename__ = "lifecycle_operations"

    id = Column(Integer, primary_key=True, index=True)

    approval_request_id = Column(
        Integer,
        ForeignKey("approval_requests.id"),
        nullable=True,
        index=True
    )

    operation_type = Column(String(100), nullable=False)

    target_user_id = Column(String(100), nullable=True, index=True)
    target_user_email = Column(String(255), nullable=True)

    requested_by = Column(String(255), nullable=True)

    status = Column(String(50), nullable=False, default="DRY_RUN")

    preview_payload = Column(Text, nullable=True)
    executed_payload = Column(Text, nullable=True)
    verification_result = Column(Text, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    executed_at = Column(DateTime, nullable=True)


class IdentityTimelineEvent(Base):
    """
    Category 11 - write path for timeline entries generated by the new
    approval/execution functionality. Existing AuditLog rows are read
    separately (not duplicated here) when a timeline is assembled.
    """

    __tablename__ = "identity_timeline_events"

    id = Column(Integer, primary_key=True, index=True)

    identity_user_id = Column(String(100), nullable=True, index=True)
    identity_email = Column(String(255), nullable=True, index=True)

    event_category = Column(String(50), nullable=False)
    event_type = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)

    actor_email = Column(String(255), nullable=True)
    old_value = Column(Text, nullable=True)
    new_value = Column(Text, nullable=True)

    related_approval_id = Column(Integer, nullable=True)
    related_operation_id = Column(Integer, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
